### ISSUE TITLE
我有一些小建议

### ISSUE THREAD

**Issue by Minecraftpe2007** [gitofleonardo/AnyText#1]
你好呀，开发者，对于编辑的内容，退出app后文本内容还原，这个是bug还是什么原因，我想通过这个模块达到“汉化”的目的，以后的更新能解决卜ava

**Comment by gitofleonardo** [comment]
您好，这个模块仅仅是修改的运行时内存的数据，在应用结束或者界面重建后，数据都会被覆盖，是不能用来汉化的。后续的版本也不会推出“汉化”功能，因为这跟本软件的运作方式不一样。
